//
// Author: zyz
// Date: 2019-11-20 10:27:29
//

export const USER = {
  SET_LOGIN_GET_TEST: 'SET_LOGIN_GET_TEST', //歌单列表
  SET_BANNER_LIST: 'SET_BANNER_LIST', //banner轮播实现
  SET_PLAYLIST_DETAIL:'SET_PLAYLIST_DETAIL',//歌单详情
  SET_MUSIC_URL:'SET_MUSIC_URL',//歌曲url
  SET_USER_MUSIC_DAN:'SET_USER_MUSIC_DAN'//获取用户歌单
};
